import type { Book, Order, Rental } from "./types"

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 12.99,
    rentPrice: 3.0,
    condition: "Used - Good",
    genre: "Classic",
    image: "/placeholder.jpg",
    rating: 4.5,
    reviews: 120,
    seller: "Bookworm Haven",
    location: "New York, NY",
    delivery: true,
    pickup: true,
  },
  {
    id: "2",
    title: "1984",
    author: "George Orwell",
    price: 10.5,
    rentPrice: 2.5,
    condition: "New",
    genre: "Dystopian",
    image: "/placeholder.jpg",
    rating: 4.8,
    reviews: 200,
    seller: "Literary Finds",
    location: "Brooklyn, NY",
    delivery: false,
    pickup: true,
  },
  {
    id: "3",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 9.75,
    rentPrice: 2.0,
    condition: "Used - Fair",
    genre: "Classic",
    image: "/placeholder.jpg",
    rating: 4.6,
    reviews: 150,
    seller: "Page Turner",
    location: "Queens, NY",
    delivery: true,
    pickup: false,
  },
  {
    id: "4",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 15.0,
    rentPrice: 3.5,
    condition: "Used - Like New",
    genre: "Fantasy",
    image: "/placeholder.jpg",
    rating: 4.9,
    reviews: 300,
    seller: "Fantasy Realm",
    location: "Manhattan, NY",
    delivery: true,
    pickup: true,
  },
  {
    id: "5",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 8.99,
    rentPrice: 1.8,
    condition: "Used - Good",
    genre: "Romance",
    image: "/placeholder.jpg",
    rating: 4.4,
    reviews: 90,
    seller: "Classic Reads",
    location: "Bronx, NY",
    delivery: false,
    pickup: true,
  },
  {
    id: "6",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: 11.25,
    rentPrice: 2.7,
    condition: "New",
    genre: "Literary Fiction",
    image: "/placeholder.jpg",
    rating: 4.2,
    reviews: 110,
    seller: "Modern Classics",
    location: "Staten Island, NY",
    delivery: true,
    pickup: true,
  },
]

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    items: [
      {
        bookId: "1",
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        price: 12.99,
        image: "/placeholder.jpg",
        quantity: 1,
        type: "buy",
      },
      {
        bookId: "5",
        title: "Pride and Prejudice",
        author: "Jane Austen",
        price: 8.99,
        image: "/placeholder.jpg",
        quantity: 1,
        type: "buy",
      },
    ],
    totalAmount: 23.74, // 12.99 + 8.99 + tax + shipping
    status: "Delivered",
    orderDate: "2024-06-15T10:30:00Z",
    paymentMethod: "Credit Card",
    deliveryAddress: "123 Main St, Anytown, USA",
  },
  {
    id: "ORD-002",
    items: [
      {
        bookId: "6",
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        price: 11.25,
        image: "/placeholder.jpg",
        quantity: 1,
        type: "buy",
      },
    ],
    totalAmount: 17.15, // 11.25 + tax + shipping
    status: "Shipped",
    orderDate: "2024-07-01T14:00:00Z",
    paymentMethod: "App Wallet",
    deliveryAddress: "456 Oak Ave, Otherville, USA",
  },
]

export const mockRentals: Rental[] = [
  {
    id: "RENT-001",
    bookId: "2",
    title: "1984",
    author: "George Orwell",
    image: "/placeholder.jpg",
    rentalPrice: 2.5,
    rentalDuration: 2, // weeks
    startDate: "2024-07-01T09:00:00Z",
    dueDate: "2024-07-15T09:00:00Z",
    status: "Active",
    seller: "Literary Finds",
  },
  {
    id: "RENT-002",
    bookId: "4",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    image: "/placeholder.jpg",
    rentalPrice: 3.5,
    rentalDuration: 1, // week
    startDate: "2024-06-20T11:00:00Z",
    dueDate: "2024-06-27T11:00:00Z",
    status: "Returned",
    seller: "Fantasy Realm",
  },
]
