import type { Book, Order, Rental, Notification, WalletTransaction } from "./types"

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 12.99,
    rentPrice: 3.0,
    condition: "Used - Good",
    genre: "Classic",
    image: "https://m.media-amazon.com/images/I/81TLiZrasVL._UF1000,1000_QL80_.jpg",
    rating: 4.5,
    reviews: 120,
    seller: "Bookworm Haven",
    location: "New York, NY",
    delivery: true,
    pickup: true,
  },
  {
    id: "2",
    title: "1984",
    author: "George Orwell",
    price: 10.5,
    rentPrice: 2.5,
    condition: "New",
    genre: "Dystopian",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327144697i/3744438.jpg",
    rating: 4.8,
    reviews: 200,
    seller: "Literary Finds",
    location: "Brooklyn, NY",
    delivery: false,
    pickup: true,
  },
  {
    id: "3",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 9.75,
    rentPrice: 2.0,
    condition: "Used - Fair",
    genre: "Classic",
    image: "https://m.media-amazon.com/images/I/71t2jj68CXL._UF1000,1000_QL80_.jpg",
    rating: 4.6,
    reviews: 150,
    seller: "Page Turner",
    location: "Queens, NY",
    delivery: true,
    pickup: false,
  },
  {
    id: "4",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 15.0,
    rentPrice: 3.5,
    condition: "Used - Like New",
    genre: "Fantasy",
    image: "https://m.media-amazon.com/images/I/91ZX8zNpwZL._UF1000,1000_QL80_.jpg",
    rating: 4.9,
    reviews: 300,
    seller: "Fantasy Realm",
    location: "Manhattan, NY",
    delivery: true,
    pickup: true,
  },
  {
    id: "5",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 8.99,
    rentPrice: 1.8,
    condition: "Used - Good",
    genre: "Romance",
    image: "https://m.media-amazon.com/images/I/81Scutrtj4L._UF1000,1000_QL80_.jpg",
    rating: 4.4,
    reviews: 90,
    seller: "Classic Reads",
    location: "Bronx, NY",
    delivery: false,
    pickup: true,
  },
  {
    id: "6",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: 11.25,
    rentPrice: 2.7,
    condition: "New",
    genre: "Literary Fiction",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyhrB1wa2AP3cPGuc-c0RiHw-U71I37wy3WQ&s",
    rating: 4.2,
    reviews: 110,
    seller: "Modern Classics",
    location: "Staten Island, NY",
    delivery: true,
    pickup: true,
  },
]

export const mockOrders: Order[] = [
  {
    id: "ORD-20240701-001",
    items: [
      {
        bookId: "1",
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        price: 12.99,
        image: "/placeholder.svg?height=300&width=200",
        quantity: 1,
        type: "buy",
        seller: "Bookworm Haven",
      },
      {
        bookId: "5",
        title: "Pride and Prejudice",
        author: "Jane Austen",
        price: 8.99,
        image: "/placeholder.svg?height=300&width=200",
        quantity: 1,
        type: "buy",
        seller: "Classic Reads",
      },
    ],
    totalAmount: 23.74,
    status: "Delivered",
    orderDate: "2024-07-01T10:30:00Z",
    paymentMethod: "Credit Card",
    deliveryAddress: "123 Main St, Anytown, USA",
  },
  {
    id: "ORD-20240625-002",
    items: [
      {
        bookId: "6",
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        price: 11.25,
        image: "/placeholder.svg?height=300&width=200",
        quantity: 1,
        type: "buy",
        seller: "Modern Classics",
      },
    ],
    totalAmount: 17.15,
    status: "Shipped",
    orderDate: "2024-06-25T14:00:00Z",
    paymentMethod: "Wallet",
    deliveryAddress: "456 Oak Ave, Otherville, USA",
  },
]

export const mockRentals: Rental[] = [
  {
    id: "RENT-20240705-001",
    bookId: "2",
    title: "1984",
    author: "George Orwell",
    image: "/placeholder.svg?height=300&width=200",
    rentalPrice: 2.5,
    rentalDuration: 2,
    startDate: "2024-07-05T09:00:00Z",
    dueDate: "2024-07-19T09:00:00Z",
    status: "Active",
    seller: "Literary Finds",
    paymentMethod: "UPI",
  },
  {
    id: "RENT-20240620-002",
    bookId: "4",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    image: "/placeholder.svg?height=300&width=200",
    rentalPrice: 3.5,
    rentalDuration: 1,
    startDate: "2024-06-20T11:00:00Z",
    dueDate: "2024-06-27T11:00:00Z",
    status: "Returned",
    seller: "Fantasy Realm",
    paymentMethod: "Wallet",
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "order",
    icon: null,
    title: "Order Delivered!",
    description: "Your order ORD-20240701-001 containing 'The Great Gatsby' has been delivered.",
    date: "2024-07-10T10:00:00Z",
    link: "/my-orders",
    read: false,
  },
  {
    id: "notif-2",
    type: "rental",
    icon: null,
    title: "Rental Due Soon",
    description: "Your rental for '1984' is due in 2 days. Please return it on time.",
    date: "2024-07-12T14:30:00Z",
    link: "/my-rentals",
    read: false,
  },
  {
    id: "notif-3",
    type: "message",
    icon: null,
    title: "New Message from Bookworm Haven",
    description: "You have a new message regarding your recent purchase.",
    date: "2024-07-11T09:15:00Z",
    link: "/messages",
    read: true,
  },
  {
    id: "notif-4",
    type: "wishlist",
    icon: null,
    title: "Price Drop Alert!",
    description: "'The Hobbit' on your wishlist just dropped to $14.00!",
    date: "2024-07-09T18:00:00Z",
    link: "/marketplace",
    read: false,
  },
]

export const mockWalletTransactions: WalletTransaction[] = [
  {
    id: "WTXN-20240710-001",
    type: "deposit",
    amount: 100.0,
    date: "2024-07-10T10:00:00Z",
    description: "Initial wallet setup",
    method: "Credit Card",
  },
  {
    id: "WTXN-20240711-002",
    type: "payment",
    amount: -23.74,
    date: "2024-07-11T14:30:00Z",
    description: "Book purchase",
    method: "Wallet",
    orderId: "ORD-20240701-001",
  },
  {
    id: "WTXN-20240712-003",
    type: "deposit",
    amount: 50.0,
    date: "2024-07-12T09:15:00Z",
    description: "Wallet top-up",
    method: "UPI",
  },
  {
    id: "WTXN-20240705-004",
    type: "payment",
    amount: -5.4, // 2.5 * 2 weeks + tax
    date: "2024-07-05T09:00:00Z",
    description: "Book rental",
    method: "Wallet",
    rentalId: "RENT-20240705-001",
  },
]
